# Generated by Django 5.1.7 on 2025-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumusers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
